// <auto-generated />
using MaternityWard;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaternityWard.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20210626173353_PrimaryKeyMonthWorkHours")]
    partial class PrimaryKeyMonthWorkHours
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("MaternityWard.MonthWorkHours", b =>
                {
                    b.Property<float>("Hours")
                        .HasColumnType("REAL");

                    b.Property<string>("WorkerId")
                        .HasColumnType("TEXT");

                    b.HasIndex("WorkerId");

                    b.ToTable("MonthWorkHours");
                });

            modelBuilder.Entity("MaternityWard.Price", b =>
                {
                    b.Property<string>("PriceName")
                        .HasColumnType("TEXT");

                    b.Property<float>("PriceValue")
                        .HasColumnType("REAL");

                    b.HasKey("PriceName");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("MaternityWard.RankBonus", b =>
                {
                    b.Property<string>("Rank")
                        .HasColumnType("TEXT");

                    b.Property<float>("BonusPercentages")
                        .HasColumnType("REAL");

                    b.Property<string>("PriceName")
                        .HasColumnType("TEXT");

                    b.HasKey("Rank");

                    b.HasIndex("PriceName");

                    b.ToTable("Bonuses");
                });

            modelBuilder.Entity("MaternityWard.Worker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("HourlyWage")
                        .HasColumnType("REAL");

                    b.Property<string>("WorkerType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("MaternityWard.MonthWorkHours", b =>
                {
                    b.HasOne("MaternityWard.Worker", "Worker")
                        .WithMany()
                        .HasForeignKey("WorkerId");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("MaternityWard.RankBonus", b =>
                {
                    b.HasOne("MaternityWard.Price", null)
                        .WithMany("Bonuses")
                        .HasForeignKey("PriceName");
                });

            modelBuilder.Entity("MaternityWard.Price", b =>
                {
                    b.Navigation("Bonuses");
                });
#pragma warning restore 612, 618
        }
    }
}
