// <auto-generated />
using MaternityWard;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MaternityWard.Migrations
{
    [DbContext(typeof(SqliteDbContext))]
    [Migration("20210626154717_AddBonuses")]
    partial class AddBonuses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("MaternityWard.Bonus", b =>
                {
                    b.Property<string>("BonousName")
                        .HasColumnType("TEXT");

                    b.Property<float>("PriceName")
                        .HasColumnType("REAL");

                    b.HasKey("BonousName");

                    b.ToTable("Bonuses");
                });

            modelBuilder.Entity("MaternityWard.Price", b =>
                {
                    b.Property<string>("PriceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("BonusBonousName")
                        .HasColumnType("TEXT");

                    b.Property<float>("PriceValue")
                        .HasColumnType("REAL");

                    b.HasKey("PriceName");

                    b.HasIndex("BonusBonousName");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("MaternityWard.Worker", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("HourlyWage")
                        .HasColumnType("REAL");

                    b.Property<string>("WorkerType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("MaternityWard.Price", b =>
                {
                    b.HasOne("MaternityWard.Bonus", null)
                        .WithMany("Prices")
                        .HasForeignKey("BonusBonousName");
                });

            modelBuilder.Entity("MaternityWard.Bonus", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
